repos:
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-toml
  - id: check-yaml
