version: "3"

services:
  ai_driver:
    build:
      context: ./ai_driver
      dockerfile: Dockerfile
    container_name: ai_driver
    ports:
      - 28001:28001
    volumes:
      - ./ai_driver/ai_driver:/code
      - ./artifacts:/artifacts
      # - ~/.cache/huggingface:/home/appuser/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
  dungeon_driver:
    build:
      context: ./dungeon_driver
      dockerfile: ./dungeon_driver/Dockerfile
    container_name: dungeon_driver
    ports:
      - 18010:18010
    volumes:
      - ./dungeon_driver/dungeon_driver:/code
    env_file:
      - .env
