version: "3"

services:
  ai_driver:
    build: 
      context: ./
      dockerfile: ./ai_driver/Dockerfile
    container_name: ai_driver
    ports:
      - 28010:28010
    volumes:
      - .:/code
      - ~/.cache/huggingface:/home/appuser/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  dungeon_driver:
    build: 
      context: ./
      dockerfile: ./dungeon_driver/Dockerfile
    container_name: dungeon_driver
    ports:
      - 18010:18010
    volumes:
      - .:/code
