from dungeon_driver.webui.dnd_qa_tab import create_dnd_qa
from dungeon_driver.webui.spell_surge_tab import create_spell_surge_generator
from dungeon_driver.webui.chat_tab import create_chat_interface
